package game.utils;

import game.configs.GameConfig;
import game.game_enums.ClearType;

public class ScreenManager {
    private static final String LOGO =

            "\u2591\u2588\u2591\u2591\u2591\u2580\u2588\u2580\u2591\u2588\u2580\u2580\u2591\u2588\u2591\u2588\u2591\u2580" +
                    "\u2588\u2580\u2591\u2588\u2580\u2580\u2591\u2588\u2580\u2588\u2591\u2588\u2591\u2588\u2591\u2580\u2588\u2580\n" +

                    "\u2591\u2588\u2591\u2591\u2591\u2591\u2588\u2591\u2591\u2588\u2591\u2588\u2591\u2588\u2580\u2588\u2591\u2591" +
                    "\u2588\u2591\u2591\u2580\u2580\u2588\u2591\u2588\u2591\u2588\u2591\u2588\u2591\u2588\u2591\u2591\u2588\u2591\n" +

                    "\u2591\u2580\u2580\u2580\u2591\u2580\u2580\u2580\u2591\u2580\u2580\u2580\u2591\u2580\u2591\u2580\u2591\u2591" +
                    "\u2580\u2591\u2591\u2580\u2580\u2580\u2591\u2580\u2580\u2580\u2591\u2580\u2580\u2580\u2591\u2591\u2580\u2591";

    private static final String RULES =
            """
                    [Rules]:
                    * Goal: Turn all tiles to the "%c" symbol to win.
                    * Move: enter row and column separated by the "%c" (e.g., "2%c3").
                    * Effect: clicking a tile toggles that tile and its four orthogonal neighbors (if present).""";

    private static final String IMPORTANT = """
            [Important]:
            * If the console text appears garbled or illegible, try changing the font.
            * Puzzles generated by the program are solvable.""";

    private static final String GAME_CONFIG = """                
            [Game Config]:
            * Width: %d,
            * Height: %d,
            * Randomized: %b""";

    public void showStartScreen() {
        // Logo
        System.out.println(LOGO);
        System.out.println();

        // Rules section
        System.out.printf(RULES,
                GameConfig.NOT_TOGGLED_SYMBOL,
                GameConfig.DELIMITER_CHAR, GameConfig.DELIMITER_CHAR
        );
        System.out.println("\n");

        // Important section
        System.out.println(IMPORTANT);
        System.out.println();

        // Config section
        System.out.printf(GAME_CONFIG,
                GameConfig.BOARD_WIDTH,
                GameConfig.BOARD_HEIGHT,
                GameConfig.IS_RANDOMIZED);
        System.out.println("\n");
    }

    public void showEndScreen(int moves) {
        System.out.println("* Congrats! You won.");
        System.out.printf("* You spent %d moves.\n", moves);
    }

    public void clearScreen() {
        if (GameConfig.CLEAR_TYPE == ClearType.RIS) System.out.println("\u001Bc");
        else if (GameConfig.CLEAR_TYPE == ClearType.PRINTLN) System.out.println("\n");
        else if (GameConfig.CLEAR_TYPE == ClearType.CURSOR_HOME_CLEAR) System.out.println("\u001b[H\u001b[2J");
        else throw new IllegalArgumentException("Wrong clear type provided.");
    }

    public void showExitScreen() {
        System.out.println("\n* Quiting...");
    }
}
